### ISSUE TITLE
problem with make library on linux

### ISSUE THREAD

**Issue by christianPetrucci** [greatyao/asmlibrary#6]
hi when i use make command in linux folder i have this error:

petrucci@christian-petrucci:~$ cd asmlibrary-master/
petrucci@christian-petrucci:~/asmlibrary-master$ cd linux/
petrucci@christian-petrucci:~/asmlibrary-master/linux$ make
g++  -I/usr/local/include/opencv -O2 -Wall -pg -g -MD  -c -o demo_fit.o ../src/demo_fit.cpp
../src/demo_fit.cpp: In function ‘int main(int, char**)’:
../src/demo_fit.cpp:88:6: warning: variable ‘camera_idx’ set but not used [-Wunused-but-set-variable]
  int camera_idx = 0;
      ^
g++  -I/usr/local/include/opencv -O2 -Wall -pg -g -MD  -c -o vjfacedetect.o ../src/vjfacedetect.cpp	
g++  -I/usr/local/include/opencv -O2 -Wall -pg -g -MD  -c -o video_camera.o ../src/video_camera.cpp	
g++ -pg -o fit vjfacedetect.o video_camera.o demo_fit.o  -L/usr/local/lib -lcv -lcxcore -lhighgui -Wl,-rpath=./ -L./ -lasmlibrary 
/usr/bin/ld: impossibile trovare -lcv
/usr/bin/ld: impossibile trovare -lcxcore
/usr/bin/ld: impossibile trovare -lhighgui
/usr/bin/ld: saltato .//libasmlibrary.so incompatibile durante la ricerca di -lasmlibrary
/usr/bin/ld: impossibile trovare -lasmlibrary
collect2: error: ld returned 1 exit status
make: *** [fit] Errore 1
petrucci@christian-petrucci:~/asmlibrary-master/linux$ ^C
petrucci@christian-petrucci:~/asmlibrary-master/linux$

**Comment by greatyao** [comment]
now fixed
