### ISSUE TITLE
missing asmbuilding

### ISSUE THREAD

**Issue by albertaleksieiev** [greatyao/asmlibrary#8]
Hi! I was trying to compile demo_build.cpp but I have an issue with missing asmbuilding class from library.

g++ giving me response
`for architecture x86_64:
  "asmbuilding::BuildDetectMapping(char const**, int, char const**, int, bool (*)(asm_shape&, _IplImage const*))", referenced from:
      _main in demo_build.o
  "asmbuilding::Train(char const**, int, char const**, int, bool, int, double, int, ASM_PROFILE_TYPE)", referenced from:
      _main in demo_build.o
  "asmbuilding::Write(char const*)", referenced from:
      _main in demo_build.o
  "asmbuilding::asmbuilding()", referenced from:
      _main in demo_build.o
  "asmbuilding::~asmbuilding()", referenced from:
      _main in demo_build.o`

I was trying to find inside .dylib file, but they give me empty response
`nm -n  libasmlibrary.dylib| grep "asmbuilding" `
When I trying to find "asmfitting", they give me positive answer.
`nm -n  libasmlibrary.dylib| grep "asmfitting" 
0000000000009510 T __ZN10asmfittingC2Ev
00000000000095c0 T __ZN10asmfittingC1Ev
0000000000009670 T __ZN10asmfittingD2Ev
0000000000009750 T __ZN10asmfittingD1Ev
0000000000009760 T __ZN10asmfitting4ReadEPKc
0000000000009950 T __ZN10asmfitting16OpticalFlowAlignER9asm_shapePK9_IplImage
0000000000009e00 T __ZN10asmfitting7FittingER9asm_shapePK9_IplImagei
0000000000009e90 T __ZN10asmfitting8Fitting2EP9asm_shapeiPK9_IplImagei
0000000000009f40 T __ZN10asmfitting12ASMSeqSearchER9asm_shapePK9_IplImageibi
000000000000a100 T __ZN10asmfitting4DrawEP9_IplImageRK9asm_shape
000000000067afe0 b __ZZN10asmfitting16OpticalFlowAlignER9asm_shapePK9_IplImageE4Soln
000000000067afe8 b __ZGVZN10asmfitting16OpticalFlowAlignER9asm_shapePK9_IplImageE4Soln
000000000067aff0 b __ZZN10asmfitting12ASMSeqSearchER9asm_shapePK9_IplImageibiE7isfirst`

**Comment by greatyao** [comment]
asmlibrary does not support building for macos

**Comment by albertaleksieiev** [comment]
@greatyao thanks! 
Can you share your asmbuilding source file?
